//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraBilisim_Teknik_Mulakat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muzik
    {
        public int Id { get; set; }
        public string SarkiAdi { get; set; }
        public string AlbumIsmi { get; set; }
        public string Artist { get; set; }
        public string SarkiSure { get; set; }
        public Nullable<int> CikisYili { get; set; }
    }
}
